server:
  port: 9006

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000

spring:
  config:
    import: optional:configserver:http://localhost:9001/
  application:
    name: feign-consumer2
  cloud:
    config:
      name: cloud-config
      profile: ${spring.profiles.active}
      label: master
  profiles:
    active: test

eureka:
  client:
    service-url:
      defaultZone: ${registercenter.eureka.defaultzone}

