server:
  port: 9002

#spring:
#  cloud:
#    config:
#      uri: http://127.0.0.1:9001
#      name: config-server
#      profile: ${config.profile:dev}
#eureka:
#  client:
#    service-url: http://localhost:9000/eureka/
