server:
  port: 9005

eureka:
  client:
    service-url:
      defaultZone: ${registercenter.eureka.defaultzone}
spring:
  config:
    import: optional:configserver:http://localhost:9001
  application:
    name: config-client2
  cloud:
    config:
      name: cloud-config
      profile: ${spring.profiles.active}
      label: master
  profiles:
    active: test

#spring:
#  cloud:
#    config:
#      uri: http://127.0.0.1:9001
#      name: config-server
#      profile: ${config.profile:dev}