server:
  port: 9001

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/causeThenEffect/spring-learn.git
          search-paths: config-git/simple
  application:
    name: config-server
